#!/bin/bash

# Setup local environment variables for React app
# Copies VITE_* variables from .env.self-hosted to .env

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "=============================================="
echo "  Setup Local Environment Variables"
echo "=============================================="
echo ""

# Check if .env.self-hosted exists
if [ ! -f .env.self-hosted ]; then
    echo "❌ .env.self-hosted not found!"
    exit 1
fi

# Backup current .env if it exists
if [ -f .env ]; then
    echo -e "${YELLOW}⚠${NC} Backing up current .env to .env.cloud-backup"
    cp .env .env.cloud-backup
fi

# Extract VITE variables from .env.self-hosted
echo -e "${BLUE}Step 1:${NC} Extracting local Supabase settings..."
source .env.self-hosted

# Create new .env with local settings
cat > .env << EOF
# Local Self-Hosted Supabase Configuration
# Generated by setup-local-env.sh
# To restore Lovable Cloud, restore from .env.cloud-backup

VITE_SUPABASE_URL=$VITE_SUPABASE_URL
VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
VITE_SUPABASE_PROJECT_ID=local
EOF

echo -e "${GREEN}✓${NC} Created .env with local settings"
echo ""
echo "Configuration:"
echo "  VITE_SUPABASE_URL: $VITE_SUPABASE_URL"
echo "  VITE_SUPABASE_PROJECT_ID: local"
echo ""
echo -e "${GREEN}✓${NC} Environment setup complete!"
echo ""
echo "Next steps:"
echo "  1. Start containers: sudo docker-compose -f docker-compose.self-hosted.yml up -d"
echo "  2. Rebuild app: sudo docker-compose -f docker-compose.self-hosted.yml up -d --build app"
echo "  3. Verify: sudo ./scripts/verify-local-connection.sh"
echo ""
echo "To restore Lovable Cloud later: cp .env.cloud-backup .env"
